# Generated by Django 2.1.7 on 2020-01-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20200123_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.CharField(error_messages={'unique': 'This email has already been registered.'}, max_length=100, unique=True),
        ),
    ]
